# .github/workflows/nodejs.yml
name: Build and Deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get version from tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Update package.json version
        uses: jossef/action-set-json-field@master
        with:
          file: package.json
          field: version
          value: ${{ steps.vars.outputs.tag }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: yarn install and build
        run: |
          yarn
          yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.vars.outputs.tag }}
          path: |
            build
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          target: ${{ secrets.REMOTE_DIR }}
          strip_components: 1
          source: "build"
